server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: Viyaan@11
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  application:
    name: PRODUCT_SERVICE
#logging:
#  level:
#    root: INFO
#    org.hibernate.SQL: DEBUG


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  service-url:
    defaultZone: http://localhost:8761/eureka


