server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
      import: configserver:http://localhost:9296

  cloud:
    gateway:
      routes:
        - id: ORDER_SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: PRODUCT_SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

